authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp.views import main, products


urlpatterns = [
    path('', main, name='index'),
    path('products/', products, name='products'),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Product Categories'

    def __str__(self):
        return  self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images', blank=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return  f'{self.name} | {self.category.name}'

mainapp/views.py
from django.shortcuts import render

from basketapp.models import Basket
from mainapp.models import ProductCategory, Product
from django.shortcuts import get_object_or_404


def main(request):
    context = {'title': 'GeekShop',
               'descriptoins': 'Новые образы и лучшие бренды на GeekShop Store.\nБесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.'}
    return render(request, 'mainapp/index.html', context)


def products(request, pk=None):
    print(pk)

    title = 'продукты'
    links_menu = ProductCategory.objects.all()

    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    if pk:
        if pk == '0':
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products,
            'basket': basket,
        }

        return render(request, 'mainapp/products_list.html', content)

    same_products = Product.objects.all()[3:5]

    content = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products
    }

    return render(request, 'mainapp/products.html', content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="auth/login.html">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="auth/profile.html">Валерий П.
                        <i class="fas fa-user-circle"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Выйти <i class="fas fa-sign-out-alt"></i></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/mainapp/inc_menu.html
{% if user.is_authenticated %}
<li>
    <a href="{% url 'auth:edit' %}">
        {{ user.first_name|default:'Пользователь' }}
    </a>
</li>
{% endif %}
<li>
    {% if user.is_authenticated %}
      <a href="{% url 'auth:logout' %}">выйти</a>
    {% else %}
      <a href="{% url 'auth:login' %}">войти</a>
    {% endif %}
</li>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        {{ descriptoins }}
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    {% for product in products_menu %}
                        <a href="#" class="list-group-item">{{ product }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-1.jpg"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-2.jpg"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-3.jpg"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                            <a href="#">
                                <img class="card-img-top"
                                     src="/media/{{product.image}}"
                                     alt="">
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#">{{ product.name }}</a>
                                </h4>
                                <h5>{{ product.price }} руб.</h5>
                                <p class="card-text">{{ product.short_description }}</p>
                            </div>
                            <div class="card-footer text-center">
                                <button type="button" class="btn btn-outline-success">Отправить в корзину</button>
                            </div>
                        </div>
                        </div>
                    {% endfor %}

                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    </ul>
                </nav>

            </div>

        </div>

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop {% now "Y" %}</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu %}
  <div class="hero-white">
    <div class="header clearfix">
      {% include 'mainapp/includes/inc_menu.html' %}
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
      <div class="title clearfix">
        <h2>
          Категория: "{{ category.name|title }}"
        </h2>
      </div>
      <div class="category-products clearfix">
        {% for product in products %}
          <div class="block">
            <a href="{% url 'basket:add' product.pk %}">
              <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
              <div class="text">
                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                <h4>{{ product.name }}</h4>
                <p>{{ product.description }} </p>
              </div>
            </a>
          </div>
        {% endfor %}

      </div>
    </div>
  </div>

  <div class="clr"></div>

{% endblock %}